# PostgreSQL. Versions 8.2 and up are supported.
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: spider_development
  #username: spider
  #password:
  #host: localhost
  #port: 5432
  #schema_search_path: myapp,sharedapp,public
  #min_messages: notice

test:
  <<: *default
  database: spider_test

production:
  <<: *default
  database: spider_production
  username: spider
  password: <%= ENV['SPIDER_PASSWORD'] %>
